version: '2'
services:
  influxdb:
    image: influxdb:1.2
    ports:
      - "8086:8086"
      - "8083:8086"
      - "8090:8090"
      - "8099:8099"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1

  telegraf:
    image: telegraf:1.2-alpine
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8125:8125"
    depends_on:
      - influxdb
      - grafana

  grafana:
    image: grafana/grafana:4.1.1
    volumes:
      - ./conf/:/etc/grafana/scripts
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

networks:
  default:
    external:
      name: docker_default
